faiss_db:
  collection_name: "document_portal"


embedding_model:
  provider: "azure"
  model_name: "text-embedding-ada-002"

retriever:
  top_k: 10

llm:

  azure:
    provider: "azure"
    model_name: "gpt-5-chat"
    temperature: 0.2
    max_output_tokens: 2048

  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
